- name: Expand quay_root
  shell: 'echo {{ quay_root }}'
  register: expanded_quay_root_output

- name: Expand quay_storage
  shell: 'echo {{ quay_storage }}'
  register: expanded_quay_storage_output

- name: Expand sqlite_storage
  shell: 'echo {{ sqlite_storage }}'
  register: expanded_sqlite_storage_output

- name: Set expanded variables
  set_fact:
    expanded_sqlite_storage: "{{ expanded_sqlite_storage_output.stdout }}"
    expanded_quay_root: "{{ expanded_quay_root_output.stdout }}"
    expanded_quay_storage: "{{ expanded_quay_storage_output.stdout }}"
