- name: Check if sqlite migration tool image is loaded
  command: podman inspect --type=image {{ sqlite_image }}
  register: db_sqlite
  ignore_errors: yes

- name: Create necessary directory for storing quay postgres db snapshot
  ansible.builtin.file:
    path: "{{ quay_root }}/quay-postgres-backup"
    mode: 0750
    state: directory
    recurse: yes

- name: Get connection string of running PostgreSQL container
  containers.podman.podman_container_info:
    name: quay-postgres
  register: postgres_container_info

- set_fact:
    postgres_connection_string: "postgresql://{{ postgres_container_info.containers[0].network_settings.ip_address }}:5432/quay"

- name: Run db-to-sqlite command
  command: >
    podman run --rm
    -v {{ quayRoot }}/quay-postgres-backup:/app
    -e CONNECTION_STRING=" {{ postgres_connection_string}}"
    {{ sqlite_image }}
    quay_sqlite.db --all

- name: Stop Quay service
  systemd:
    name: quay-app.service
    enabled: no
    daemon_reload: yes
    state: stopped
    force: yes
    scope: "{{ systemd_scope }}"

- name: Create Sqlite storage named volume
  containers.podman.podman_volume:
      state: present
      name: sqlite-storage

- name: Copy data to pg-storage volume
  command: podman cp { quayRoot }}/quay-postgres-backup/quay_sqlite.db quay-app:/quay-registry/sqlite/data/quay_sqlite.db

- name: Stop Postgres service
  systemd:
    name: quay-postgres.service
    enabled: no
    daemon_reload: yes
    state: stopped
    force: yes
    scope: "{{ systemd_scope }}"

- name: Start Quay service
  systemd:
    name: quay-app.service
    enabled: yes
    daemon_reload: yes
    state: restarted
    scope: "{{ systemd_scope }}"
